    version: "3"
    services:
      selenoid:
        platform: linux/amd64
        image: aerokube/selenoid:latest-release
        container_name: selenoid
        network_mode: bridge
        ports:
          - "4444:4444"
        environment:
          - "OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/video"
        volumes:
          - "./selenoid/config/browsers.json:/etc/selenoid/browsers.json:ro"
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/etc/selenoid:/etc/selenoid"
          - "./video:/opt/selenoid/video"
        command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "20", "-retry-count", "1000", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-max-timeout", "20m0s", "-session-attempt-timeout", "15m", "-timeout", "10m",  "-service-startup-timeout", "10m"]
      selenoid-ui:
        platform: linux/amd64
        image: aerokube/selenoid-ui:latest-release
        container_name: selenoid-ui
        network_mode: bridge
        ports:
          - "8080:8080"
        links:
          - selenoid
        command: -selenoid-uri 'http://selenoid:4444'
        depends_on:
          - selenoid