name: tests

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  build-test-coverage:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Install Google Chrome
        run: |
          brew install --cask google-chrome

      - name: Install Firefox
        run: |
          brew install --cask firefox

      - name: Set up properties file
        run: printf "%s" "${{ secrets.PROPERTIES }}" > src/main/java/com/core/utils/configuration.properties

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run api tests
        run: ./gradlew clean api

      - name: Run smoke tests
        run: ./gradlew clean smoke





